import * as THREE from 'three'
import _ from 'lodash'
import config from '../config'

function selectionConfigToAnswerData(selectionConfig, extraConfigs) {
  let {
    center3,
    dimensions3,
    xDirection3,
    yDirection3,
    zDirection3,
    numberOfSlices,
    thickness,
    spacing,
    maxRotationOff,
    sequenceType,
    fatSuppression,
    inversionRecovery,
    echoTime,
    inversionTime,
    flipAngle,
    repetitionTime,
    fieldStrength,
    frequencyMatrix,
    phaseMatrix,
    frequencyVoxelSize,
    phaseVoxelSize,
    oversampling,
    windowWidth,
    windowLevel,
    kernel,
    rotationTime,
    beamSelected,
    pitch,
    averages,
    canDragAboveTR,
    concatenations,
    scanTime,
    elapsedTime,
    lostWindowFocus,
    pixelShift,
    receiverBandWidth,
    snr,
    flatFactor,
    falloffFactor,
    trEfficiency,
    minConcatAcqPackage,
    vendorStyle,
    partialFourier,
    parallelFactor,
    echoSpacing,
    echoTrainLength,
    enableTSEBlur,
    enableCruncherBasicLab,
    enableCruncherResolution,
    enableBitDepth8,
    enableFovWrap,
    enableCompactMode,
    enableResolution,
    swapPhase,
    noiseFactor,
    echoOrdering,
    sliceSelection,
    limitedCTModelPlanes,
    breathingInstruction,
    cardiacAcquisitionType,
    rWaveDelay,
    ignoreBadBeats,
    badBeatsTolerance,
    kvp,
    rfPulsing,
    gradientRamp,
    specialtyOption,
    diffusionDirections,
    numBValues,
    bValues,
    bAverages,
    bValueLower,
    bValueUpper,
    diffusionADC,
    minSeqTe,
    ctdi,
    dlp,
    tubeCurrent,
  } = selectionConfig
  return _.extend(
    {
      xDirectionX: xDirection3.x,
      xDirectionY: xDirection3.y,
      xDirectionZ: xDirection3.z,
      yDirectionX: yDirection3.x,
      yDirectionY: yDirection3.y,
      yDirectionZ: yDirection3.z,
      zDirectionX: config.isCTLab ? zDirection3.x : yDirection3.x,
      zDirectionY: config.isCTLab ? zDirection3.y : yDirection3.y,
      zDirectionZ: config.isCTLab ? zDirection3.z : yDirection3.z,
      centerX: center3.x,
      centerY: center3.y,
      centerZ: center3.z,
      dimensionX: dimensions3.x,
      dimensionY: dimensions3.y,
      dimensionZ: dimensions3.z,
      numberOfSlices,
      thickness,
      spacing,
      maxRotationOff, // only for Single Slice (only on IdentType Max) - this is how much the student may get the angle/rotation wrong before their score starts going down
      sequenceType, // for Contrast Lab
      fatSuppression,
      inversionRecovery,
      echoTime,
      repetitionTime,
      inversionTime,
      flipAngle,
      fieldStrength,
      frequencyMatrix,
      phaseMatrix,
      frequencyVoxelSize,
      phaseVoxelSize,
      oversampling,
      windowWidth,
      windowLevel,
      kernel,
      isCTLab: config.isCTLab,
      rotationTime,
      beamSelected,
      pitch,
      averages,
      canDragAboveTR,
      concatenations,
      echoSpacing,
      echoTrainLength,
      enableTSEBlur,
      enableCruncherBasicLab,
      enableCruncherResolution,
      enableBitDepth8,
      enableFovWrap,
      enableCompactMode,
      enableResolution,
      swapPhase,
      noiseFactor,
      echoOrdering,
      sliceSelection,
      limitedCTModelPlanes,
      selectionConfigToAnswerData,
      scanTime,
      elapsedTime,
      lostWindowFocus,
      pixelShift,
      receiverBandWidth,
      snr,
      flatFactor,
      falloffFactor,
      trEfficiency,
      minConcatAcqPackage,
      vendorStyle,
      partialFourier,
      parallelFactor,
      breathingInstruction,
      cardiacAcquisitionType,
      rWaveDelay,
      ignoreBadBeats,
      badBeatsTolerance,
      kvp,
      rfPulsing,
      gradientRamp,
      specialtyOption,
      diffusionDirections,
      numBValues,
      bValues,
      bAverages,
      bValueLower,
      bValueUpper,
      diffusionADC,
      minSeqTe,
      ctdi,
      dlp,
      tubeCurrent,
    },
    extraConfigs
  )
}

// the opposite of selectionConfigToAnswerData
function answerDataToSelectionConfig(answerData) {
  let {
    xDirectionX,
    xDirectionY,
    xDirectionZ,
    yDirectionX,
    yDirectionY,
    yDirectionZ,
    zDirectionX,
    zDirectionY,
    zDirectionZ,
    centerX,
    centerY,
    centerZ,
    dimensionX,
    dimensionY,
    dimensionZ,
    numberOfSlices,
    thickness,
    spacing,
    maxRotationOff,
    sequenceType,
    fatSuppression,
    inversionRecovery,
    echoTime,
    repetitionTime,
    inversionTime,
    flipAngle,
    fieldStrength,
    frequencyMatrix,
    phaseMatrix,
    frequencyVoxelSize,
    phaseVoxelSize,
    windowWidth,
    windowLevel,
    kernel,
    limitedCTModelPlanes,
    zDirectionBias,
    testPatientGender,
    testPatientModelId,
    listPatientPositionsAndBodyBox,
    isMRIShowHeadHolder,
    rotationTime,
    beamSelected,
    pitch,
    averages,
    canDragAboveTR,
    concatenations,
    scanTime,
    elapsedTime,
    lostWindowFocus,
    pixelShift,
    receiverBandWidth,
    snr,
    flatFactor,
    falloffFactor,
    trEfficiency,
    minConcatAcqPackage,
    vendorStyle,
    partialFourier,
    parallelFactor,
    echoSpacing,
    echoTrainLength,
    breathingInstruction,
    cardiacAcquisitionType,
    rWaveDelay,
    ignoreBadBeats,
    badBeatsTolerance,
    satBands,
    scanDuration,
    kvp,
    rfPulsing,
    gradientRamp,
    specialtyOption,
    diffusionDirections,
    numBValues,
    bValues,
    bAverages,
    bValueLower,
    bValueUpper,
    diffusionADC,
    scanDelay,
    ctdi,
    dlp,
    tubeCurrent,
    enableCruncherBasicLab,
    enableCruncherResolution,
    enableBitDepth8,
    enableFovWrap,
    enableCompactMode,
    enableResolution,
    swapPhase,
    noiseFactor,
  } = answerData

  // not sure if answerData always has zDirection (could just cross X Y, in that case...)
  let zDirection3 = _.isNil(zDirectionX) ? null : new THREE.Vector3(zDirectionX, zDirectionY, zDirectionZ)

  return {
    center3: new THREE.Vector3(centerX, centerY, centerZ),
    dimensions3: new THREE.Vector3(dimensionX, dimensionY, dimensionZ),
    xDirection3: new THREE.Vector3(xDirectionX, xDirectionY, xDirectionZ),
    yDirection3: new THREE.Vector3(yDirectionX, yDirectionY, yDirectionZ),
    zDirection3,
    numberOfSlices,
    thickness,
    spacing,
    maxRotationOff,
    sequenceType,
    fatSuppression,
    inversionRecovery,
    echoTime,
    inversionTime,
    flipAngle,
    repetitionTime,
    fieldStrength,
    frequencyMatrix,
    phaseMatrix,
    frequencyVoxelSize,
    phaseVoxelSize,
    windowWidth,
    windowLevel,
    kernel,
    limitedCTModelPlanes,
    zDirectionBias,
    testPatientGender,
    testPatientModelId,
    listPatientPositionsAndBodyBox,
    isMRIShowHeadHolder,
    rotationTime,
    beamSelected,
    pitch,
    averages,
    canDragAboveTR,
    concatenations,
    echoSpacing,
    scanTime,
    elapsedTime,
    lostWindowFocus,
    pixelShift,
    receiverBandWidth,
    snr,
    flatFactor,
    falloffFactor,
    trEfficiency,
    minConcatAcqPackage,
    vendorStyle,
    partialFourier,
    parallelFactor,
    echoTrainLength,
    breathingInstruction,
    cardiacAcquisitionType,
    rWaveDelay,
    ignoreBadBeats,
    badBeatsTolerance,
    satBands,
    scanDuration,
    kvp,
    rfPulsing,
    gradientRamp,
    specialtyOption,
    diffusionDirections,
    numBValues,
    bValues,
    bAverages,
    bValueLower,
    bValueUpper,
    diffusionADC,
    scanDelay,
    ctdi,
    dlp,
    tubeCurrent,
    enableCruncherBasicLab,
    enableCruncherResolution,
    enableBitDepth8,
    enableFovWrap,
    enableCompactMode,
    enableResolution,
    swapPhase,
    noiseFactor,
  }
}

// Covert vector3 to data {x, y, z}
function vector3ToData(vector) {
  return { x: vector.x, y: vector.y, z: vector.z }
}

// Covert data {x, y, z} to vector3
function dataToVector3(data) {
  return new THREE.Vector3(data.x, data.y, data.z)
}

// Check vector 1 is equal vector 2
function isVector3Equal(v1, v2) {
  return v1.x == v2.x && v1.y == v2.y && v1.z == v2.z
}

function createLineGeometry() {
  let geometry = new THREE.Geometry()
  geometry.vertices.push(new THREE.Vector3())
  geometry.vertices.push(new THREE.Vector3())
  return geometry
}

// https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep
// await sleep(1000);
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

// Like Bluebird's Promise.props: http://bluebirdjs.com/docs/api/promise.props.html
//  from: https://stackoverflow.com/a/50437423
async function promiseProps(object) {
  return _.zipObject(_.keys(object), await Promise.all(_.values(object)))
}

const isContrastLab = (name) => name.includes('Contrast Lab')

export {
  sleep,
  isContrastLab,
  createLineGeometry,
  answerDataToSelectionConfig,
  selectionConfigToAnswerData,
  promiseProps,
  vector3ToData,
  dataToVector3,
  isVector3Equal,
}
