export function activeLabelUtil(labType) {
  console.log('inside util', labType)
  switch (labType) {
    case 'ultra':
      return {
        numberOfSlices: true,
        spacing: true,
        phaseEncoding: true,
        oversampling: true,
        dimensions3x: true,
        dimensions3y: true,
        thickness: true,
        repetitionTime: true,
        echoTime: true,
        averages: true,
        concatenations: true,
        magnPreparation: true,
        inversionTime: true,
        flipAngle: true,
        frequencyMatrix: true,
        phaseMatrix: true,
        accelerationMode: true,
        parallelFactor: true,
        partialFourier: true,
        sequenceType: true,
        receiverBandWidth: true,
        echoTrainLength: true,
        echoSpacing: true,
        fatSuppression: true,
      }
    case 'contrast':
      return {
        numberOfSlices: true,
        spacing: true,
        phaseEncoding: true,
        oversampling: false,
        dimensions3x: true,
        dimensions3y: true,
        thickness: true,
        repetitionTime: true,
        echoTime: true,
        averages: false,
        concatenations: false,
        magnPreparation: false,
        inversionTime: false,
        flipAngle: false,
        frequencyMatrix: false,
        phaseMatrix: false,
        accelerationMode: false,
        parallelFactor: false,
        partialFourier: false,
        sequenceType: true,
        receiverBandWidth: false,
        echoTrainLength: false,
        echoSpacing: false,
        fatSuppression: false,
      }
    case 'resolution':
      return {
        numberOfSlices: true,
        spacing: true,
        phaseEncoding: true,
        oversampling: false,
        dimensions3x: true,
        dimensions3y: true,
        thickness: true,
        repetitionTime: false,
        echoTime: false,
        averages: false,
        concatenations: false,
        magnPreparation: false,
        inversionTime: false,
        flipAngle: false,
        frequencyMatrix: true,
        phaseMatrix: true,
        accelerationMode: false,
        parallelFactor: false,
        partialFourier: false,
        sequenceType: false,
        receiverBandWidth: false,
        echoTrainLength: false,
        echoSpacing: false,
        fatSuppression: false,
      }
    case 'basic':
      return {
        numberOfSlices: true,
        spacing: true,
        phaseEncoding: true,
        oversampling: false,
        dimensions3x: true,
        dimensions3y: true,
        thickness: true,
        repetitionTime: false,
        echoTime: false,
        averages: false,
        concatenations: false,
        magnPreparation: false,
        inversionTime: false,
        flipAngle: false,
        frequencyMatrix: false,
        phaseMatrix: false,
        accelerationMode: false,
        parallelFactor: false,
        partialFourier: false,
        sequenceType: false,
        receiverBandWidth: false,
        echoTrainLength: false,
        echoSpacing: false,
        fatSuppression: false,
      }
    // ... other exam types
    default:
      return {}
  }
}
